# Generated by Django 3.2 on 2021-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zipcode')),
                ('special_date', models.DateField(verbose_name='Date')),
                ('special_date_name', models.CharField(choices=[('B', 'Birthday'), ('A', 'Anniversary'), ('S', 'Special Occasion')], default='B', max_length=1)),
                ('phone', models.CharField(max_length=10, verbose_name='Phone #')),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default=0, max_length=1)),
            ],
        ),
    ]
