# Generated by Django 3.1.7 on 2021-04-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210420_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone #'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='special_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zipcode'),
        ),
    ]
